### ISSUE TITLE
Offset parameter and reverse animation request

### ISSUE THREAD

**Issue by mysticeti** [haishuangsu/path_animation#1]
Hi

First of all great package, it simplifies path animation a lot. Is it possible to add offsets as a parameter so that when the child widgets are being added to the same path they do not start at the same path. There needs to be some gap defined by the call. 

For instance
```
List<Widget> grid = [];

    Path roundedRectanglePath = Path()
      ..addRRect(RRect.fromRectAndRadius(
          Rect.fromLTWH(deviceSize.width * 0.05, deviceSize.height * 0.02,
              deviceSize.width * 0.85, deviceSize.height * 0.72),
          Radius.circular(10)));

    for (int i = 0; i < 8; i++) {
      grid.add(
        Positioned(
          left: 0.0,
          top: 0.0,
          child: PathAnimation(
            path: roundedRectanglePath,
            // The path to set  to animated.
            duration: const Duration(seconds: 5),
            repeat: true,
            curve: Curves.slowMiddle,
            drawPath: true,
            pathColor: Colors.red,
            pathWidth: 1,
            child: const Icon( Icons.flutter_dash,
            size: 30,),
          ),
        ),
      );
    }
```

Another feature I would like to request is reverse animation currently everything moves in clockwise direction, is it possible to add a reverse parameter so that widgets also translate the opposite direction i.e. counter-clockwise direction.

**Comment by haishuangsu** [comment]
Thanks for your suggestion, the new version now supports reverse animation. Regarding your first suggestion, it sounds a bit like customization, which conflicts with the general function, maybe you can show the effect?

**Comment by mysticeti** [comment]
Hi
I think it can be added as general function by using offsets along that path could be in percentage or fraction. The following image shows what I am trying to achieve. In the same path there could be multiple widgets following that path but with gaps between them that can adjusted by the user. The widgets would still follow the path in loop. the paths can be overlapped using stack but unfortunately the starting position for the widgets following the path cannot be adjusted. Let me know if the explanation is not clear.

![multiple images on the same path](https://github.com/haishuangsu/path_animation/assets/18485958/3a978fb1-936b-4739-ba4a-cac4c1a25727)

**Comment by haishuangsu** [comment]
new version now is support, you can try to set the Arg - startAnimatedPercent.
