### ISSUE TITLE
path changes

### ISSUE THREAD

**Issue by cksoft0807** [haishuangsu/path_animation#3]
Thanks for the component. I have registered a small error when the path changes (layout builder). the new path is drawn correctly, but the widget moves on the original path.

**Comment by haishuangsu** [comment]
thx for your feedback, could you provider the example?

**Comment by haishuangsu** [comment]
> Thanks for the component. I have registered a small error when the path changes (layout builder). the new path is drawn correctly, but the widget moves on the original path.

The issue is fix, you can try to update to the newest version. thanks you your feedback.

**Comment by cksoft0807** [comment]
Sorry for the delay. Yes, working fine now. 

t@nx
